# Generated by Django 3.2.3 on 2021-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=128, verbose_name='ID пользователя slack')),
                ('wikiworks_domain', models.CharField(blank=True, max_length=128, verbose_name='Портал пользователя wikiworks')),
                ('wikiworks_login', models.CharField(blank=True, max_length=128, verbose_name='Логин пользователя wikiworks')),
                ('wikiworks_password', models.CharField(blank=True, max_length=128, verbose_name='Пароль пользователя wikiworks')),
            ],
        ),
        migrations.CreateModel(
            name='SentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_msg_id', models.CharField(max_length=64, verbose_name='ID отправленного сообщения')),
            ],
        ),
    ]
